---
title: "Intergenic tract analysis"
author: Ahmed Hasan
output: pdf_document
---

```{r}
library(tidyverse)
library(fs)
library(here)


din1 <- 6.34375
din2 <- 3.385417
```

## Load data

```{r}
assign_bins <- function(d) {
  out <- d %>%
    mutate(
      bin = case_when(
        tract_size <= 2000 ~ 'short',
        tract_size > 2000 & tract_size <= 4000 ~ 'medium',
        tract_size > 4000 & tract_size <= 8000 ~ 'long',
        tract_size > 8000 ~ 'extended'
      )
    )
  return(out)
}

assign_bins_2kb <- function(d) {
  out <- d %>% 
    mutate(
      bin = case_when(
        tract_size <= 2000 ~ 'short',
        tract_size > 2000 ~ 'long'
      )
    )
  return(out)
}

# tracts
d <- here('data/correlates/intergenic_tract_rho.tsv') %>% 
  read_tsv(col_types = cols()) %>% 
  filter(tract_size > 0) %>% 
  assign_bins_2kb()

# utrs
utr5_tracts <- here('data/correlates/utr_tract_rho.tsv') %>% 
  read_tsv(col_types = cols()) %>% 
  filter(tract_size > 0) %>% 
  assign_bins_2kb()

utr3_tracts <- here('data/correlates/utr3_tract_rho.tsv') %>% 
  read_tsv(col_types = cols()) %>% 
  left_join(d, by = c('chrom', 'start', 'end')) %>% 
  filter(!is.na(bin))

# flanks of tracts 
flank_2kb <- here('data/correlates/intergenic_flanks_2kb.tsv') %>% 
  read_tsv(col_types = cols()) %>% 
  left_join(
    select(d, -tract_size), by = c('chrom', 'start', 'end')
  )

non_flank_2kb <- flank_2kb %>% 
  filter(tract_size > 2000) %>% 
  mutate(rho_vals = rho_vals - (left_vals + right_vals),
         rho_count = rho_count - (left_count + right_count))
```


## UTRs

```{r}
utr_bars <- utr5_tracts %>% 
  group_by(bin) %>% 
  summarise(
    total_rho = sum(utr_rho_vals),
    total_count = sum(utr_rho_count),
    sd_rho = sd(utr_rho_window),
    n = n()
  ) %>% 
  ungroup() %>% 
  mutate(
    mean_rho = total_rho / total_count,
    se_rho = sd_rho / sqrt(n)
  )

utr3_bars <- utr3_tracts %>% 
  group_by(bin) %>% 
  summarise(
    total_rho = sum(utr3_rho_vals),
    total_count = sum(utr3_rho_count),
    sd_rho = sd(utr3_rho_window),
    n = n()
  ) %>% 
  ungroup() %>% 
  mutate(
    mean_rho = total_rho / total_count,
    se_rho = sd_rho / sqrt(n)
  )

utr_bars_all <- bind_rows(utr_bars, utr3_bars, .id = 'name') %>% 
  mutate(utr = case_when(
    name == 1 ~ 'five_prime',
    name == 2 ~ 'three_prime')
  )
```

Bootstrapping:

```{r}
utr_boot_fxn <- function(d, rep_count, tract_type) {
  boot_obj <- replicate(rep_count, {
    
    sampled_rows <- d %>% 
      filter(bin == tract_type) %>% 
      sample_frac(size = 1, replace = TRUE)
    
    out <- sum(sampled_rows$utr_rho_vals) / sum(sampled_rows$utr_rho_count)
    return(out)
  })
  
  message(paste('Completed sampling for', tract_type))
  boot_obj <- na.omit(boot_obj)
  
  conf_df <- broom::tidy(t.test(boot_obj, alternative = 'two.sided', mu = 0, conf.level = 0.95)) %>% 
    select(estimate, p.value, conf.low, conf.high) %>% 
    mutate(bin = tract_type)
  return(conf_df)
}

utr_boot_fxn(utr5_tracts, 100, 'long')

utr5_cis <- c('short', 'long') %>% 
  map_dfr(~ utr_boot_fxn(utr5_tracts, 1000, .)) %>% 
  mutate(utr = 'five_prime')
utr3_cis <- c('short', 'long') %>% 
  map_dfr(~ utr_boot_fxn(
    rename(
      utr3_tracts, utr_rho_vals = utr3_rho_vals, utr_rho_count = utr3_rho_count), 
    1000, .)) %>% 
  mutate(utr = 'three_prime')

utr_cis <- bind_rows(utr5_cis, utr3_cis)

utr_bars_cis <- utr_bars_all %>% 
  left_join(utr_cis, by = c('utr', 'bin'))

# utr_bars_cis <- read_csv(here('data/correlates/utr_bars_cis.csv'), col_types = cols())

# write_csv(utr_bars_cis, here('data/correlates/utr_bars_cis_new.csv'))

utr_bars_cis %>% 
  filter(utr == 'five_prime') %>% 
  ggplot(aes(x = bin, y = mean_rho)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  geom_errorbar(width = 0.4, position = position_dodge(width = 0.9),
    aes(ymin = conf.low, ymax = conf.high)) +
  theme_minimal() +
  scale_x_discrete(limits = c('short', 'long')) # add flank rho to this plot
```

## Tract rho (full tract + non-flank tract)

```{r}
tracts_all <- d %>% 
  group_by(bin) %>% 
  summarise(
    total_rho_vals = sum(rho_vals),
    total_rho_count = sum(rho_count),
    sd_rho = sd(rho_window),
    n = n()
  ) %>% 
  mutate(mean_rho = total_rho_vals / total_rho_count) %>% 
  mutate(type = 'tract')

# for >2 kb - only take 'non upstream' (ie 'non right window') sequence
# for short, use tracts_all

flank_2kb_mean <- flank_2kb %>% 
  filter(bin == 'long') %>% 
  select(-starts_with('left')) %>%
  mutate(non_flank_rho = rho_vals - right_vals,
         non_flank_count = rho_count - right_count) %>% 
  group_by(bin) %>% 
  summarise(
    total_rho_vals = sum(right_vals),
    total_rho_count = sum(right_count),
    sd_rho = sd(right_window),
    n = n()
  ) %>% 
  mutate(mean_rho = total_rho_vals / total_rho_count) %>% 
  mutate(type = 'flank')

flank_2kb_non_flank <- flank_2kb %>% 
  filter(bin == 'long') %>% 
  select(-starts_with('left')) %>%
  mutate(non_flank_rho = rho_vals - right_vals,
         non_flank_count = rho_count - right_count,
         non_flank_window = non_flank_rho / non_flank_count) %>% 
  group_by(bin) %>% 
  summarise(
    total_rho_vals = sum(non_flank_rho),
    total_rho_count = sum(non_flank_count),
    sd_rho = total_rho_vals / total_rho_count,
    n = n()
  ) %>% 
  mutate(mean_rho = total_rho_vals / total_rho_count) %>% 
  mutate(type = 'non-flank')
  
tracts_flanks <- bind_rows(
  tracts_all, flank_2kb_mean, flank_2kb_non_flank
)
```

Bootstrapping:

```{r}
tract_boot_fxn <- function(d, rep_count, tract_type) {
  boot_obj <- replicate(rep_count, {
    
    sampled_rows <- d %>% 
      filter(bin == tract_type) %>% 
      sample_frac(size = 1, replace = TRUE)
    
    out <- sum(sampled_rows$rho_vals) / sum(sampled_rows$rho_count)
    return(out)
  })
  
  message(paste('Completed sampling for', tract_type))
  boot_obj <- na.omit(boot_obj)
  
  conf_df <- broom::tidy(t.test(boot_obj, alternative = 'two.sided', 
                                mu = 0, conf.level = 0.95)) %>% 
    select(estimate, p.value, conf.low, conf.high) %>% 
    mutate(bin = tract_type)
  return(conf_df)
}

tracts_cis <- c('short') %>% 
  map_dfr(~ tract_boot_fxn(d, 1000, .)) %>% 
  mutate(type = 'tract')
flanks_cis <- c('long') %>% 
  map_dfr(~ 
    tract_boot_fxn(
      select(flank_2kb, rho_vals = right_vals, rho_count = right_count, bin),
    1000, .)) %>% 
  mutate(type = 'flank')
non_flank_cis <- c('long') %>% 
  map_dfr(~ tract_boot_fxn(flank_2kb %>% 
    select(-starts_with('left')) %>%
    mutate(rho_vals = rho_vals - right_vals,
           rho_count = rho_count - right_count)
    , 1000, .)) %>% 
  mutate(type = 'non-flank')

tract_cis_all <- bind_rows(tracts_cis, flanks_cis, non_flank_cis) %>% 
  left_join(tracts_flanks, by = c('type', 'bin')) %>% 
  mutate(bar = paste(bin, type))

# write_csv(tract_cis_all, path = here('data/correlates/tract_cis_new.csv'))

ggplot(tract_cis_all, aes(x = bin, y = mean_rho, fill = type)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  geom_errorbar(width = 0.4, position = position_dodge(width = 0.9),
                aes(ymin = conf.low, ymax = conf.high)) +
  scale_x_discrete(limits = c('short', 'long')) +
  geom_hline(yintercept = 0.0041, linetype = 'dashed')
```

## Putting it all together

```{r}
cis_all <- utr_bars_cis %>% 
  select(-name) %>% 
  filter(utr == 'five_prime') %>% 
  select(-utr) %>% 
  mutate(type = 'utr5') %>% 
  bind_rows(tract_cis_all)

cis_all

# write_csv(cis_all, path = here('data/correlates/cis_all_new.csv'))

ggplot(cis_all, aes(x = bin, y = mean_rho, fill = type)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  geom_errorbar(width = 0.4, position = position_dodge(width = 0.9),
                aes(ymin = conf.low, ymax = conf.high)) +
  scale_x_discrete(limits = c('short', 'medium', 'long', 'extended'),
                   labels = c('<2kb', '2-4kb', '4-8kb', '>8kb')) +
  geom_hline(yintercept = 0.0041, linetype = 'dashed') +
  labs(
    x = 'tract length'
  ) +
  theme_minimal()
```






































